// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGyzsS-cX67g2KjLmneK6vLUVdEoNpdqw',
    appId: '1:129764271799:web:059ae398186f828f994f32',
    messagingSenderId: '129764271799',
    projectId: 'wellpets-9fde2',
    authDomain: 'wellpets-9fde2.firebaseapp.com',
    storageBucket: 'wellpets-9fde2.firebasestorage.app',
    measurementId: 'G-QDKN3ST0G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmOJkI5c9xtMe_dUUCsgJZBmbAwmcibXM',
    appId: '1:129764271799:android:2ab7a8f0433d65af994f32',
    messagingSenderId: '129764271799',
    projectId: 'wellpets-9fde2',
    storageBucket: 'wellpets-9fde2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsLhH-iEtJHp1fvbBklUKBOQ_vQmknv94',
    appId: '1:129764271799:ios:4694d9dee0e19fe4994f32',
    messagingSenderId: '129764271799',
    projectId: 'wellpets-9fde2',
    storageBucket: 'wellpets-9fde2.firebasestorage.app',
    iosBundleId: 'com.example.wellpets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsLhH-iEtJHp1fvbBklUKBOQ_vQmknv94',
    appId: '1:129764271799:ios:4694d9dee0e19fe4994f32',
    messagingSenderId: '129764271799',
    projectId: 'wellpets-9fde2',
    storageBucket: 'wellpets-9fde2.firebasestorage.app',
    iosBundleId: 'com.example.wellpets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGyzsS-cX67g2KjLmneK6vLUVdEoNpdqw',
    appId: '1:129764271799:web:44ac905735d4bd6e994f32',
    messagingSenderId: '129764271799',
    projectId: 'wellpets-9fde2',
    authDomain: 'wellpets-9fde2.firebaseapp.com',
    storageBucket: 'wellpets-9fde2.firebasestorage.app',
    measurementId: 'G-7BNP53YPLS',
  );
}
