trigger:
  branches:
    include:
      - main  # Cambia por el nombre de tu rama principal

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseFlutterTool@0
  inputs:
    version: '1.0.0+1'
- script: |
    flutter pub get
    flutter build apk --release
  displayName: 'Compilar aplicación Flutter'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'C:\AppWell\Wellpets\app\build\app\outputs\flutter-apk'
    ArtifactName: 'release-apk'
