trigger:
  branches:
    include:
      - main  # Cambia por el nombre de tu rama principal

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseFlutterTool@0
  inputs:
    version: 'stable'  # Usa la versión estable de Flutter

- script: |
    flutter pub get
    flutter build apk --release
  displayName: 'Compilar aplicación Flutter'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build/app/outputs/flutter-apk/'  # Ruta relativa para agentes Linux
    ArtifactName: 'release-apk'
    publishLocation: 'Container'
